#!/usr/bin/env bash
#
# symgen.sh -- read a symbol manifest produced by the recipe loop and
# emit two artifacts the link step consumes:
#
#   <out>/wasm_deps.inc        -- foreign-symbol registrations, one per
#                                 line, included by wasm_extras.inc.
#   <out>/wasm_deps_uflags.txt -- one -Wl,-u,<sym> per line so wasm-ld
#                                 doesn't strip symbols nothing else
#                                 references before Sforeign_symbol can
#                                 take their address. Splice into the
#                                 final emcc link via $(< file).
#
# Usage: symgen.sh <symbols-manifest> <out-dir>
# The manifest is one C symbol name per line (blank lines and #-comments
# are skipped). Symbols are deduplicated and sorted for stable output.
#
# Both outputs are written atomically: skipped (mtime unchanged) when
# the new content matches the existing file, so incremental builds
# don't pointlessly re-link.

set -euo pipefail

if [ $# -ne 2 ]; then
  echo "usage: $0 <symbols-manifest> <out-dir>" >&2
  exit 2
fi

manifest=$1
out_dir=$2

mkdir -p "$out_dir"

# Collect, dedupe, sort.
syms=$(grep -v '^\s*\(#\|$\)' "$manifest" | sort -u || true)

inc_tmp=$(mktemp "${TMPDIR:-/tmp}/wasm_deps.inc.XXXXXX")
uflags_tmp=$(mktemp "${TMPDIR:-/tmp}/wasm_deps_uflags.txt.XXXXXX")
trap 'rm -f "$inc_tmp" "$uflags_tmp"' EXIT

{
  printf '/* AUTO-GENERATED by symgen.sh -- do not edit by hand.\n'
  printf '   Foreign-symbol registrations for the WASM build, drawn\n'
  printf '   from the deps/ recipe manifest. Included by wasm_extras.inc. */\n'
  # extern with empty parens lets us take the address of any C symbol
  # without knowing its real signature. The cast to (void *) discards
  # the (unspecified) function type for Sforeign_symbol's table. This
  # only clashes if a real prototype for the same name is already in
  # scope here -- recipes for libraries whose headers boot.c happens
  # to include must instead register by hand in wasm_extras.inc.
  if [ -n "$syms" ]; then
    while IFS= read -r s; do
      printf '{ extern void %s(); Sforeign_symbol("%s", (void *)%s); }\n' \
        "$s" "$s" "$s"
    done <<< "$syms"
  fi
} > "$inc_tmp"

if [ -n "$syms" ]; then
  while IFS= read -r s; do
    printf -- '-Wl,-u,%s\n' "$s"
  done <<< "$syms" > "$uflags_tmp"
else
  : > "$uflags_tmp"
fi

# Atomic-ish replace: only mv if content differs, so dependent rebuilds
# trigger only on real changes.
_install() {
  local src=$1 dst=$2
  if [ -f "$dst" ] && cmp -s "$src" "$dst"; then
    return 0
  fi
  mv "$src" "$dst"
}
_install "$inc_tmp" "$out_dir/wasm_deps.inc"
_install "$uflags_tmp" "$out_dir/wasm_deps_uflags.txt"
