#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# SCRIPT_DIR=`pwd`
SRC_DIR="$SCRIPT_DIR/racket/src"

TARGET_MACHINE=tpb32l
CROSS_DIR="$SRC_DIR/build-cs-$TARGET_MACHINE/cross-root/$TARGET_MACHINE"
COMPILED_FILE_ROOT="$SCRIPT_DIR/build/zo"

#  -X $CROSS_DIR/collects \
echo exec "$SCRIPT_DIR/racket/bin/racket" --cross-compiler $TARGET_MACHINE $CROSS_DIR/lib \
    -MCR $COMPILED_FILE_ROOT: \
    -X $CROSS_DIR/collects \
    -G $CROSS_DIR/etc \
    "$@"

exec "$SCRIPT_DIR/racket/bin/racket" --cross-compiler $TARGET_MACHINE $CROSS_DIR/lib \
    -MCR $COMPILED_FILE_ROOT: \
    -X $CROSS_DIR/collects \
    -G $CROSS_DIR/etc \
    "$@"
