#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$SCRIPT_DIR/.."
SRC_DIR="$ROOT_DIR/racket/src"

TARGET_MACHINE=tpb32l
CROSS_DIR="$SRC_DIR/build-cs-$TARGET_MACHINE/cross-root/$TARGET_MACHINE"
COMPILED_FILE_ROOT="$ROOT_DIR/build/zo"

: ${RACKET:=$ROOT_DIR/racket/bin/racket}

exec "$RACKET" --cross-compiler $TARGET_MACHINE $CROSS_DIR/lib \
    -MCR $COMPILED_FILE_ROOT: \
    -X $CROSS_DIR/collects \
    -G $CROSS_DIR/etc \
    "$@"
